/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cloudera.impala.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TImpalaQueryOptions implements org.apache.thrift.TEnum {
  ABORT_ON_ERROR(0),
  MAX_ERRORS(1),
  DISABLE_CODEGEN(2),
  BATCH_SIZE(3),
  MEM_LIMIT(4),
  NUM_NODES(5),
  MAX_SCAN_RANGE_LENGTH(6),
  MAX_IO_BUFFERS(7),
  NUM_SCANNER_THREADS(8),
  ALLOW_UNSUPPORTED_FORMATS(9),
  DEFAULT_ORDER_BY_LIMIT(10),
  DEBUG_ACTION(11),
  ABORT_ON_DEFAULT_LIMIT_EXCEEDED(12),
  PARQUET_COMPRESSION_CODEC(13),
  HBASE_CACHING(14),
  HBASE_CACHE_BLOCKS(15);

  private final int value;

  private TImpalaQueryOptions(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TImpalaQueryOptions findByValue(int value) { 
    switch (value) {
      case 0:
        return ABORT_ON_ERROR;
      case 1:
        return MAX_ERRORS;
      case 2:
        return DISABLE_CODEGEN;
      case 3:
        return BATCH_SIZE;
      case 4:
        return MEM_LIMIT;
      case 5:
        return NUM_NODES;
      case 6:
        return MAX_SCAN_RANGE_LENGTH;
      case 7:
        return MAX_IO_BUFFERS;
      case 8:
        return NUM_SCANNER_THREADS;
      case 9:
        return ALLOW_UNSUPPORTED_FORMATS;
      case 10:
        return DEFAULT_ORDER_BY_LIMIT;
      case 11:
        return DEBUG_ACTION;
      case 12:
        return ABORT_ON_DEFAULT_LIMIT_EXCEEDED;
      case 13:
        return PARQUET_COMPRESSION_CODEC;
      case 14:
        return HBASE_CACHING;
      case 15:
        return HBASE_CACHE_BLOCKS;
      default:
        return null;
    }
  }
}
