/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.cloudera.impala.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TStatusCode implements org.apache.thrift.TEnum {
  OK(0),
  CANCELLED(1),
  ANALYSIS_ERROR(2),
  NOT_IMPLEMENTED_ERROR(3),
  RUNTIME_ERROR(4),
  MEM_LIMIT_EXCEEDED(5),
  INTERNAL_ERROR(6);

  private final int value;

  private TStatusCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TStatusCode findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return CANCELLED;
      case 2:
        return ANALYSIS_ERROR;
      case 3:
        return NOT_IMPLEMENTED_ERROR;
      case 4:
        return RUNTIME_ERROR;
      case 5:
        return MEM_LIMIT_EXCEEDED;
      case 6:
        return INTERNAL_ERROR;
      default:
        return null;
    }
  }
}
